// <auto-generated />
using System;
using Books_Spot_Task.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Books_Spot_Task.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220928143040_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Books_Spot_Task.Entities.BookEntity", b =>
                {
                    b.Property<string>("IsbnCode")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BookStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IsbnCode");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Books_Spot_Task.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("BookingCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateBorrowed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReserved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IsbnCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LibraryCardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookingCode");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
